import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

  
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body>
        
    
<center><img src="https://www.zameen.com/news/wp-content/uploads/2020/04/PBA.jpg" height={600} width={1350} alt="" /></center>

      <strong><center>State Bank Of Pakistan</center></strong>

        {children}
        <center>Pakistan Bank's Association</center>
        
      </body>
    </html>
  )
}
